use_frameworks!

platform :ios, '9.0'

target 'nutrition_Example' do
  pod 'nutrition', :path => '../'

  target 'nutrition_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
